//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMobileDevice.InstallationProxy
{
    using System.Runtime.InteropServices;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    using System;

    public partial class InstallationProxyNativeMethods
    {
        /// <include file='IInstallationProxyApi.xml' path='/IInstallationProxyApi/instproxy_client_options_add/*'/>
        [DllImport(libraryName, EntryPoint = "instproxy_client_options_add", CharSet = CharSet.Ansi, BestFitMapping = false, CallingConvention = CallingConvention.Cdecl)]
        public static extern void instproxy_client_options_add(PlistHandle client_options, string key, string value, byte term);
    }
}
