//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="iDeviceNativeMethods.cs" company="Quamotion">
// Copyright (c) 2016-2019 Quamotion. All rights reserved.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.iDevice
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    public partial class iDeviceNativeMethods
    {
        
        public static iDeviceError idevice_get_device_list(out System.Collections.ObjectModel.ReadOnlyCollection<string> devices, ref int count)
        {
            System.Runtime.InteropServices.ICustomMarshaler devicesMarshaler = iDeviceListMarshaler.GetInstance(null);
            System.IntPtr devicesNative = System.IntPtr.Zero;
            iDeviceError returnValue = iDeviceNativeMethods.idevice_get_device_list(out devicesNative, ref count);
            devices = ((System.Collections.ObjectModel.ReadOnlyCollection<string>)devicesMarshaler.MarshalNativeToManaged(devicesNative));
            devicesMarshaler.CleanUpNativeData(devicesNative);
            return returnValue;
        }
        
        public static iDeviceError idevice_get_udid(iDeviceHandle device, out string udid)
        {
            System.Runtime.InteropServices.ICustomMarshaler udidMarshaler = NativeStringMarshaler.GetInstance(null);
            System.IntPtr udidNative = System.IntPtr.Zero;
            iDeviceError returnValue = iDeviceNativeMethods.idevice_get_udid(device, out udidNative);
            udid = ((string)udidMarshaler.MarshalNativeToManaged(udidNative));
            udidMarshaler.CleanUpNativeData(udidNative);
            return returnValue;
        }
        
        public static iDeviceError idevice_get_tcp_endpoint(out string host, ref ushort port)
        {
            System.Runtime.InteropServices.ICustomMarshaler hostMarshaler = NativeStringMarshaler.GetInstance(null);
            System.IntPtr hostNative = System.IntPtr.Zero;
            iDeviceError returnValue = iDeviceNativeMethods.idevice_get_tcp_endpoint(out hostNative, ref port);
            host = ((string)hostMarshaler.MarshalNativeToManaged(hostNative));
            hostMarshaler.CleanUpNativeData(hostNative);
            return returnValue;
        }
    }
}
