//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="MobileBackupErrorExtensions.cs" company="Quamotion">
// Copyright (c) 2016-2019 Quamotion. All rights reserved.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.MobileBackup
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    public static class MobileBackupErrorExtensions
    {
        
        public static void ThrowOnError(this MobileBackupError value)
        {
            if ((value != MobileBackupError.Success))
            {
                throw new MobileBackupException(value);
            }
        }
        
        public static void ThrowOnError(this MobileBackupError value, string message)
        {
            if ((value != MobileBackupError.Success))
            {
                throw new MobileBackupException(value, message);
            }
        }
        
        public static bool IsError(this MobileBackupError value)
        {
            return (value != MobileBackupError.Success);
        }
    }
}
