//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="PinvokeErrorExtensions.cs" company="Quamotion">
// Copyright (c) 2016-2018 Quamotion. All rights reserved.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.Pinvoke
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    public static class PinvokeErrorExtensions
    {
        
        public static void ThrowOnError(this PinvokeError value)
        {
            if ((value != PinvokeError.Success))
            {
                throw new PinvokeException(value);
            }
        }
        
        public static void ThrowOnError(this PinvokeError value, string message)
        {
            if ((value != PinvokeError.Success))
            {
                throw new PinvokeException(value, message);
            }
        }
        
        public static bool IsError(this PinvokeError value)
        {
            return (value != PinvokeError.Success);
        }
    }
}
