//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="PinvokeNativeMethods.cs" company="Quamotion">
// Copyright (c) 2016-2020 Quamotion. All rights reserved.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.Pinvoke
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    public partial class PinvokeNativeMethods
    {
        
        public const string LibraryName = "imobiledevice";
        
        static PinvokeNativeMethods()
        {
            LibraryResolver.EnsureRegistered();
        }
        
        /// <summary>
        /// Frees a string that was previously allocated by libimobiledevice.
        /// </summary>
        /// <param name="string">
        /// The string to free.
        /// </param>
        /// <returns>
        /// Always returns PINVOKE_E_SUCCESS.
        /// </returns>
        [System.Runtime.InteropServices.DllImportAttribute(PinvokeNativeMethods.LibraryName, EntryPoint="pinvoke_free_string", CallingConvention=System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public static extern PinvokeError pinvoke_free_string(System.IntPtr @string);
        
        /// <summary>
        /// Gets the size of a string that was previously allocated by libimobiledevice.
        /// </summary>
        /// <param name="string">
        /// The string of which to get its size.
        /// </param>
        /// <param name="length">
        /// The length of the string, in bytes.
        /// </param>
        /// <returns>
        /// Always returns PINVOKE_E_SUCCESS.
        /// </returns>
        [System.Runtime.InteropServices.DllImportAttribute(PinvokeNativeMethods.LibraryName, EntryPoint="pinvoke_get_string_length", CallingConvention=System.Runtime.InteropServices.CallingConvention.Cdecl)]
        public static extern PinvokeError pinvoke_get_string_length(System.IntPtr @string, out ulong length);
    }
}
