//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="LockdownErrorExtensions.cs" company="Quamotion">
// Copyright (c) 2016-2019 Quamotion. All rights reserved.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.Lockdown
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    public static class LockdownErrorExtensions
    {
        
        public static void ThrowOnError(this LockdownError value)
        {
            if ((value != LockdownError.Success))
            {
                throw new LockdownException(value);
            }
        }
        
        public static void ThrowOnError(this LockdownError value, string message)
        {
            if ((value != LockdownError.Success))
            {
                throw new LockdownException(value, message);
            }
        }
        
        public static bool IsError(this LockdownError value)
        {
            return (value != LockdownError.Success);
        }
    }
}
