// <copyright file="GlobalSuppressions.cs" company="Quamotion">
// Copyright (c) Quamotion. All rights reserved.
// </copyright>

using System;
using System.CodeDom;

namespace iMobileDevice.Generator
{
    /// <summary>
    /// A type (class) which has been generated by parsing the C headers for libimobiledevice,
    /// ready to be generated using CodeDOM.
    /// </summary>
    public class CodeDomGeneratedType : IGeneratedType
    {
        public CodeDomGeneratedType(CodeTypeDeclaration declaration)
        {
            this.Declaration = declaration ?? throw new ArgumentNullException(nameof(declaration));
        }

        public CodeTypeDeclaration Declaration
        {
            get;
            private set;
        }

        public string Name => this.Declaration.Name;

        public string FileNameSuffix
        {
            get
            {
                if (this.Declaration.UserData.Contains("FileNameSuffix"))
                {
                    return (string)this.Declaration.UserData["FileNameSuffix"];
                }

                return string.Empty;
            }
        }
    }
}
