// <copyright file="GlobalSuppressions.cs" company="Quamotion">
// Copyright (c) Quamotion. All rights reserved.
// </copyright>

using iMobileDevice.Generator.Nustache;

namespace iMobileDevice.Generator
{
    /// <summary>
    /// A type (class) which has been generated by parsing the C headers for libimobiledevice,
    /// ready to be generated using Nustache.
    /// </summary>
    public class NustacheGeneratedType : IGeneratedType
    {
        public NustacheGeneratedType(NustacheType type, string template)
        {
            this.Template = template;
            this.Type = type;
        }

        public string Name => this.Type.Name;

        public string FileNameSuffix => string.Empty;

        public  NustacheType Type
        {
            get;
            set;
        }

        public string Template
        {
            get;
            set;
        }
    }
}
