//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="iDeviceActivationError.cs" company="Quamotion">
// Copyright (c) 2016-2019 Quamotion. All rights reserved.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.iDeviceActivation
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    public enum iDeviceActivationError : int
    {
        
        Success = 0,
        
        IncompleteInfo = -1,
        
        OutOfMemory = -2,
        
        UnknownContentType = -3,
        
        BuddymlParsingError = -4,
        
        PlistParsingError = -5,
        
        HtmlParsingError = -6,
        
        UnsupportedFieldType = -7,
        
        InternalError = -255,
    }
}
