//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="UsbmuxLookupOptions.cs" company="Quamotion">
// Copyright (c) 2016-2020 Quamotion. All rights reserved.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.Usbmuxd
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    /// <summary>
    /// Device lookup options for usbmuxd_get_device. 
    /// </summary>
    public enum UsbmuxLookupOptions : int
    {
        
        LookupUsbmux = 2,
        
        LookupNetwork = 4,
        
        /// <summary>
        /// prefer network connection if device is available via USBMUX *and* network 
        /// </summary>
        LookupPreferNetwork = 8,
    }
}
