//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="RecoveryDeviceInfo.cs" company="Quamotion">
// Copyright (c) 2016-2019 Quamotion. All rights reserved.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.Recovery
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public struct RecoveryDeviceInfo
    {
        
        public uint cpid;
        
        public uint cprv;
        
        public uint cpfm;
        
        public uint scep;
        
        public uint bdid;
        
        public ulong ecid;
        
        public uint ibfl;
        
        public System.IntPtr srnm;
        
        public System.IntPtr imei;
        
        public System.IntPtr ap_nonce;
        
        public uint ap_nonce_size;
        
        public System.IntPtr sep_nonce;
        
        public uint sep_nonce_size;
        
        public string srnmString
        {
            get
            {
                return Utf8Marshal.PtrToStringUtf8(this.srnm);
            }
        }
        
        public string imeiString
        {
            get
            {
                return Utf8Marshal.PtrToStringUtf8(this.imei);
            }
        }
    }
}
