//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="RecoveryDevice.cs" company="Quamotion">
// Copyright (c) 2016-2020 Quamotion. All rights reserved.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.Recovery
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public struct RecoveryDevice
    {
        
        public System.IntPtr product_type;
        
        public System.IntPtr hardware_model;
        
        public uint board_id;
        
        public uint chip_id;
        
        public System.IntPtr display_name;
        
        public string product_typeString
        {
            get
            {
                return Utf8Marshal.PtrToStringUtf8(this.product_type);
            }
        }
        
        public string hardware_modelString
        {
            get
            {
                return Utf8Marshal.PtrToStringUtf8(this.hardware_model);
            }
        }
        
        public string display_nameString
        {
            get
            {
                return Utf8Marshal.PtrToStringUtf8(this.display_name);
            }
        }
    }
}
