//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMobileDevice.InstallationProxy
{
    using System.Runtime.InteropServices;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    using System;

    public partial class InstallationProxyApi : IInstallationProxyApi
    {
        /// <include file='IInstallationProxyApi.xml' path='/IInstallationProxyApi/instproxy_client_options_add/*'/>
        public void instproxy_client_options_add(PlistHandle client_options, string key, string value, byte term)
        {
            InstallationProxyNativeMethods.instproxy_client_options_add(client_options, key, value, term);
        }
    }
}
